src/App.vue, src/assets/styles/style.scss, src/components/Pagination.vue, src/components/PoliticalParty.vue, src/components/index.js, src/constants/examples.js, src/router/index.js, src/services/factory.js, src/services/politicalPartiesServices.js, src/store/index.js, src/store/notificationStore.js, src/views/index.js, src/views/public/PoliticalParties.vue
- Makes it possible to view political parties.
**Note**: Couldn't upload images for some reason.
=> closes #12747553 | View Poilitical Parties

src/services/factory.js, src/services/subscriptionsServices.js, src/views/public/Politician.vue
- Add subscribe
- Add unsubscribe
=> closes #12765958 | Subscribe

src/assets/styles/style.scss, src/components/PoliticalParty.vue, src/router/index.js, src/services/politicalPartiesServices.js, src/views/index.js, src/views/public/PoliticalParties.vue, src/views/public/PoliticalParty.vue, src/views/public/Politician.vue
- Setup Political Party Detail Page.
=> closes #12747555 | Political Party Detail Page Setup

package-lock.json, package.json, src/components/Navbar.vue, src/store/index.js
=> closes #12763255 | Persist Store

src/assets/json/tabsList.json, src/components/Tabs.vue, src/helpers/dateUtil.js, src/services/services.js, src/views/public/Politician.vue
- Add political background to political detail page.
=> closes | Politician Background in Politician Detail Page

package-lock.json, package.json, src/assets/json/tabsList.json, src/components/QuarterlyView.vue, src/components/SideScroll.vue, src/constants/examples.js, src/directives/index.js, src/helpers/dataUtil.js, src/main.js, src/views/public/Politician.vue
- Display politicians manifesto and link to full details.
=> close | Display Manifesto

package-lock.json, package.json, src/assets/json/currencies.json, src/components/Footer.vue, src/directives/index.js, src/filters/getValue.js, src/filters/index.js, src/main.js, src/router/index.js, src/views/public/static/Donate.vue
- Adds money mask filter and directive.
=> Feature: Money Mask

src/App.vue, src/components/Alert.vue, src/components/Auth.vue, src/components/Navbar.vue, src/components/index.js, src/services/services.js, src/store/index.js, src/store/notificationStore.js, src/store/subscriptionStore.js, src/views/public/Politician.vue, src/views/public/Politicians.vue
- Show auth modal when user isn't signed in gets a 401.
=> Feature: Auth Component

src/components/Home/Subscription.vue, src/services/services.js, src/views/public/Home.vue, src/views/public/PoliticalParties.vue, src/views/public/Politicians.vue
- Integrates the new subscription endpoints.
=> Feature: Integrate Subscription

src/views/public/static/ContactUs.vue
=> Feature: Contact Us Mobile

src/views/public/static/AboutUs.vue
- Mobile changes for about us page.
=> Feature: About Us Mobile

src/components/Feeds.vue
=> Feature: Full Story

package-lock.json, src/assets/img/user-primary.svg, src/assets/styles/style.scss, src/components/CountrySelector.vue, src/components/Dropdown/Dropdown.vue, src/components/Home/Politicians.vue, src/components/Navbar.vue, tailwind.config.js
This styles the navbar in mobile view
=> Ft navbar on mobile

package.json, src/assets/img/checked.svg, src/components/Alert.vue, src/components/Checkbox.vue, src/components/Dropdown/Dropdown.vue, src/components/Politician.vue, src/components/SocialLogin.vue, src/components/index.js, src/directives/index.js, src/views/public/Home.vue, src/views/public/Politician.vue, src/views/public/accounts/Basic.vue, src/views/public/accounts/Subscriptions.vue, tailwind.config.js
- Allows the user share a politician's page.
- Removes social connect in user account page.
- Adds dropdown for subscription in user's list of subscriptions.
=> Feature: Social Share & Connect

src/assets/img/user-grey.svg, src/components/Auth.vue, src/components/Checkbox.vue, src/views/auth/SignUp.vue
- It adds the checkbox to the sign up process for subscribing
=> Feature: Signup Checkbox

src/main.js, src/views/auth/SignUp.vue
- Remove console log
- Sign Up Mobile Layout
=> Feature: Sign Up Mobile

src/components/Auth.vue, src/components/Checkbox.vue, src/components/Feeds.vue, src/components/QuarterlyView.vue, src/helpers/stringUtil.js, src/views/auth/SignUp.vue, src/views/public/Politician.vue
This adds accomplishment link accomplishments page
=> Add accomplishment link

src/components/Navbar.vue, src/components/QuarterlyView.vue, src/views/public/Home.vue, tailwind.config.js
This fixes the way home page shows up for bigger screens. It also adds a conditional for accomplishment link so that the link text shows up only if the url is present
=> Fix responsive stuff

src/components/Dropdown/DropdownItem.vue, src/components/Navbar.vue, src/services/factory.js, src/services/notificationsServices.js, src/store/index.js, src/store/notificationStore.js
- Implements notifications for clients.
=> Feature: Integrate Notifications

src/views/public/static/Donate.vue
=> Feature: Paystack Amount Fix

src/components/Home/Politicians.vue, src/components/Home/TrendingPoliticians.vue, src/components/Navbar.vue, src/components/Politician.vue, src/components/QuarterlyView.vue, src/constants/examples.js, src/helpers/dateUtil.js, src/helpers/stringUtil.js, src/views/public/Politician.vue, src/views/public/Politicians.vue
This PR:
- Adds the route for past and incoming in the leaders nav dropdown
- changes political institution to region
- Fixes issues with some dates
=> Bug add links and general cleanup

.eslintrc.js, src/services/careersServices.js, src/services/services.js, src/views/public/Career.vue, src/views/public/Careers.vue
=> Feature: Apply to Job

src/App.vue, src/assets/styles/style.scss, src/components/Auth.vue, src/components/Auth/ForgotPasswordForm.vue, src/components/Auth/PasswordResetForm.vue, src/components/Auth/SignInForm.vue, src/components/Auth/SignUpForm.vue, src/components/Auth/VerifyForm.vue, src/components/Auth/index.js, src/components/Modal.vue, src/components/SocialLogin.vue, src/components/index.js, src/layouts/Auth.vue, src/layouts/index.js, src/router/index.js, src/services/authServices.js, src/store/notificationStore.js, src/views/auth/ResetPassword.vue, src/views/auth/SignIn.vue, src/views/auth/SignUp.vue, src/views/index.js
This PR creates forms for forgot password request and and reset password
=> Ft forgot password

src/views/public/Politician.vue
=> Improvement: Realign Subscribe Button

src/assets/json/countryList.json, src/components/CountrySelector.vue
This PR allows only Nigeria to be selected from the country list both functionally and visually
=> Make other African Countries greyscale

src/components/Auth.vue, src/components/Modal.vue, src/components/Navbar.vue, src/components/Tabs.vue, src/constants/examples.js, src/router/index.js, src/views/public/Politician.vue, tailwind.config.js
[Trello card](https://trello.com/c/wlc4jYfp)
=> Fix animation on the politician page

src/components/Auth/PasswordResetForm.vue, src/components/Auth/SignInForm.vue, src/components/Auth/SignUpForm.vue, src/router/index.js
=> Feature: Minor Fixes

src/helpers/dateUtil.js, src/views/public/Politician.vue
- Update politician detail page.
=> Feedback: Political Background Change

src/views/public/static/ContactUs.vue
=> Feedback: Hide Phone and Address in contact page.

src/components/Auth/VerifyForm.vue, src/router/index.js
- Checks if the user is logged in and verified on each change in route.
- Fixes button being disabled on failed verification.
=> Feature: Verfification Fix

src/services/factory.js, src/services/supportServices.js, src/views/public/static/ContactUs.vue
- Completes a contact us page.
=> Feature: Complete Contact Us Page

package-lock.json, package.json, src/assets/json/tabsList.json, src/components/Feeds.vue, src/components/QuarterlyView.vue, src/components/SideScroll.vue, src/views/public/Politician.vue
This fixes the side scroll. Side scroll now works by either clicking on it or when the page is scrolled, the side scroll options are highlighted depending on where you are
=> Fix side scroll

src/views/public/Careers.vue
=> Fix: Career Page Infinite Loading.

src/router/index.js
- Show footer in contact us page.
=> Feature: Add Footer Page to Contact Us Page.

src/views/public/Politician.vue
- Realign subscribe button and fix some console errors.
Some of the Errors:
=> Improvement: Realign Subscription button.

src/components/Home/Politicians.vue, src/components/PoliticalParty.vue, src/components/Politician.vue
=> Feature: Center Profile Pictures

src/views/public/Politician.vue
=> Feature: Update Politician View

src/components/Alert.vue, src/components/Auth/DeleteAccountForm.vue, src/components/Auth/index.js, src/services/usersServices.js, src/views/public/accounts/Basic.vue, tailwind.config.js
[Trello task](https://trello.com/c/5rYWOdAb/33-delete-account-not-working)
=> Bug delete account not working

src/components/Auth/EditPersonalDetailsForm.vue, src/components/Auth/VerifyForm.vue, src/components/Auth/index.js, src/components/Dropdown/Dropdown.vue, src/components/Navbar.vue, src/router/accountRoutes.js, src/store/userStore.js, src/views/public/accounts/Basic.vue
- Allows you edit your name.
- Shows footer on accounts page.
- Centers number in notification circle.
=> Feature: Profile Footer & Edit Profile

src/router/index.js, src/views/public/Politician.vue
- Adds footer to the politician footer.
- Fixes animation for side view for scroll.
=> Feature: Footer Politician Page

src/views/public/PoliticalParty.vue, src/views/public/Politician.vue
- Fix the "null" date display.
- Fix twitter wrapper overlapping into footer.
=> Fix: Overlapping Twitter Wrapper & "null" date

src/components/Auth/SignUpForm.vue, src/components/Checkbox.vue
=> Feature: Social Fail Fix

src/views/public/Faqs.vue
=> Feature: Mobile View FAQ

src/views/public/Careers.vue
- Mobile view for careers page.
=> Feature: Careers Page Mobile View.

src/components/Navbar.vue, src/views/public/Politicians.vue
=> Feature: Navbar Search Field

src/components/Auth/SignInForm.vue, src/components/Auth/SignUpForm.vue, src/components/Footer.vue, src/components/Home/Subscription.vue, src/components/PoliticianSubscription.vue, src/views/public/Careers.vue, src/views/public/Faqs.vue, src/views/public/Politician.vue
- Remove shadow for mobile view in FAQ.
- Remove sitemap.
- Center menu drop down for mobile and remove filter button, show filter always.
- Add space to bottom text for login and sign up page.
- Mobile view share view.
- Mobile view relative scroll on politician page.
- show politician subscribe button always.
- Trim emails for subscription.
- Increase social icons and vote icons by 1 step.
**NOTE:** This was feedback gotten after a call with him at 1pm today, Sunday the 28th.
=> Feature: Feedback from Nosa

src/components/PoliticianSubscription.vue
- Show auth modal when a guest clicks on the subscribe button for politician.
=> Feature: Auth Modal on Subscribe for Guest

src/views/public/Politician.vue
- Fixes the scrolling bug on leaders page.
=> Feature: Scroll fix

src/components/Auth/ForgotPasswordForm.vue, src/components/Auth/SignInForm.vue, src/components/Auth/SignUpForm.vue, src/views/public/Politician.vue
- Remove error message.
- Trim email.
=> Feature: Nosa's Feedback

src/components/Home/TrendingPoliticians.vue, src/components/Tabs.vue, src/views/public/Careers.vue, src/views/public/Home.vue, src/views/public/Politician.vue, src/views/public/Politicians.vue, src/views/public/static/AboutUs.vue
=> Feature: Nosa Feedback 2

src/components/PoliticianSubscription.vue, src/views/public/Politician.vue
=> Feature: Disable Subscriptions for coming soon page

src/components/Footer.vue, src/views/public/Politicians.vue, src/views/public/static/ContactUs.vue
- Updates social login links.
- Fixes tab changes from nav bar.
=> Feature: Nosa Feedback 3

src/views/public/Politicians.vue
- Pagination and state dropdown fix
=> Release #1 - September 14, 2020

src/views/public/PoliticalParties.vue, src/views/public/Politicians.vue
- Update for political parties pagination
=> Release #2 - September 14, 2020

src/components/Pagination.vue, src/views/public/PoliticalParties.vue, src/views/public/Politician.vue, src/views/public/Politicians.vue
- Limit the pages showing in pagination
=> Release #3 - September 14, 2020
